---
- hosts: targets
  remote_user: ubuntu
  vars:
     contents: "{{ lookup('file', '/home/ubuntu/2tx_2tx_server.out') }}"
  tasks:
    - name: Start NDN-CDN server process
      shell: "(nohup sudo /usr/local/bin/nfd-start > /tmp/nfd.log 2>&1 &)"

    - name: Configure srsLTE EPC
      replace:
        path: /home/ubuntu/.config/srslte/epc.conf
        regexp: '127.0.1.100'
        replace: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
        backup: yes

    - name: Start srsEPC
      shell: "(nohup sudo srsepc </dev/null > /tmp/srsepc.log 2>&1 &)"

    - name: Add routing for srs_spgw_sgi gateway for LTE network
      shell: "(sudo iptables --table nat --append POSTROUTING --out-interface ens3 -j MASQUERADE)"

    - name: Add packet forwarding(enable packet forwarding by kernel net.ipv4.ip_forward=1) for srs_spgw_sgi gateway for LTE network
      shell: "(sudo iptables --append FORWARD --in-interface srs_spgw_sgi -j ACCEPT)"

    - name: start identify 2tx-2rx server
      shell: "(nohup /usr/bin/python /home/ubuntu/server.py  >> /tmp/server.log 2>&1 &)"

    - name: Load NDN-CDN server with howth gunrunning audio
      shell: "(nohup sudo /bin/bash /home/ubuntu/ndn-data/scripts/ndnchunks_publish.sh /home/ubuntu/ndn-data/howth_gun_running_audio/ ndn:/dp/data/cc  >> /tmp/ndnchunks_publish.log 2>&1 &)"

    - name: Load NDN-CDN server with aideens_dolmen_audio
      shell: "(nohup sudo /bin/bash /home/ubuntu/ndn-data/scripts/ndnchunks_publish.sh /home/ubuntu/ndn-data/aideens_dolmen_audio/ ndn:/dp/data/cc  >> /tmp/ndnchunks_publish.log 2>&1 &)"

    - name: Load NDN-CDN server with howth_castle_gates_audio
      shell: "(nohup sudo /bin/bash /home/ubuntu/ndn-data/scripts/ndnchunks_publish.sh /home/ubuntu/ndn-data/howth_castle_gates_audio/ ndn:/dp/data/cc  >> /tmp/ndnchunks_publish.log 2>&1 &)"

    - name: Load NDN-CDN server gunrunning image
      shell: "(nohup sudo ndnputchunks -p ndn:/dp/data/0/0 < /home/ubuntu/ndn-data/howth_gun_running_image/asgard.jpg  >> /tmp/ndnchunks_publish.log 2>&1 &)"

    - name: Load NDN-CDN server with howth_castle_gates_image
      shell: "(nohup sudo ndnputchunks -p ndn:/dp/data/1/0 < /home/ubuntu/ndn-data/howth_castle_gates_image/castlegates.jpg >> /tmp/ndnchunks_publish.log 2>&1 &)"

    - name: Load NDN-CDN server with aideens_dolmen_image
      shell: "(nohup sudo ndnputchunks -p ndn:/dp/data/2/0 < /home/ubuntu/ndn-data/aideens_dolmen_image/aideensdolmen.jpg &  >> /tmp/ndnchunks_publish.log 2>&1 &)"

    - name: Scan ports on network to find NFD process running
      shell: "(nohup sudo /home/ubuntu/dcontroller-repo/start-dcontroller.sh >> /tmp/ndnchunks_publish.log 2>&1 &)"

    - name: Create a face to wireless (OFDM) interface on LTE network
      shell: "(nohup sudo nfdc face create udp://172.16.0.1 &)"

    - name: Create a route to UE slice2
      shell: "(nohup sudo nfdc route add / udp://172.16.0.1 &)"
