---
- hosts: targets
  tasks:
# All updates disabled by default. Uncomment all the lines below to have update version of dependencies and HyDRA
#   - name: Install dependencies
#     apt:
#       name: "{{ packages }}"
#     vars:
#       packages:
#         - libzmq3-dev
#         - libfftw3-dev
#         - libopencv-dev
#         - gnuradio
#         - gnuradio-dev
#     become: yes

#   - name: Get source for GR-Hydra
#     git:
#       repo: "https://github.com/maiconkist/gr-hydra.git"
#       dest: /home/ubuntu/gr-hydra
#       version: bleeding
#       update: true
#       force: yes
#   
#   - name: Make HyDRA Directory
#     file:
#       path: /home/ubuntu/gr-hydra/build
#       state: directory
#   - name: CMake HyDRA
#     command: cmake ../
#     args:
#       chdir: /home/ubuntu/gr-hydra/build
#   - make:
#       chdir: /home/ubuntu/gr-hydra/build
#   - make:
#       chdir: /home/ubuntu/gr-hydra/build
#       target: install
#     become: yes

#   - name: Make GRC-HyDRA Directory
#     file:
#       path: /home/ubuntu/gr-hydra/grc_blocks/build
#       state: directory
#   - name: CMake HyDRA
#     command: cmake ../
#     args:
#       chdir: /home/ubuntu/gr-hydra/grc_blocks/build
#   - make:
#       chdir: /home/ubuntu/gr-hydra/grc_blocks/build
#   - make:
#       chdir: /home/ubuntu/gr-hydra/grc_blocks/build
#       target: install
#     become: yes
  
    - name: "Create tap0 interface"
      shell: |
        ip tuntap add mode tap dev tap0
        ip addr add 1.1.1.2/24 dev tap0
        ip link set dev tap0 up
      become: yes

    - name: chmod  /home/ubuntu/gr-hydra/grc_blocks/app/ansible_hydra_vr1_rx.py
      file:
        path: /home/ubuntu/gr-hydra/grc_blocks/app/ansible_hydra_vr1_rx.py
        state: file
        mode: a+x
      
    - name: Start ansible_vr1_rx.py script. Log to /tmp/
      shell: "(nohup python /home/ubuntu/gr-hydra/grc_blocks/app/ansible_hydra_vr1_rx.py </dev/null > /tmp/ansible_hydra_vr1_rx.log 2>&1 &)"

    - name: Start NFD
      shell: "(nohup sudo /usr/local/bin/nfd-start > nfd.log 2>&1 &)"

    - name: Create a face to wireless (OFDM) interface UE slice1
      shell: "(nohup sudo nfdc face create udp://1.1.1.1 &)"

    - name: Create a route to UE slice1
      shell: "(nohup sudo nfdc route add / udp://1.1.1.1 &)"
