- hosts: servers
  tasks:
    - name: Get source for GR-Hydra
      git:
        repo: "https://github.com/maiconkist/gr-hydra.git"
        dest: /home/ubuntu/gr-hydra
        version: bleeding
        update: true
        force: yes

    - name: chmod  /home/ubuntu/gr-hydra/grc_blocks/app/ansible_hydra_gr_server.py
      file:
        path: /home/ubuntu/gr-hydra/grc_blocks/app/ansible_hydra_gr_server.py
        state: file
        mode: a+x

    - name: "Start ansible_hydra_gr_server.py script. Log to /tmp/"
      shell: "(nohup python /home/ubuntu/gr-hydra/grc_blocks/app/ansible_hydra_gr_server.py --ansibleIPPort {{ hostvars[inventory_hostname]['ansible_ens4']['ipv4']['address'] }}:5000  </dev/null > /tmp/ansible_hydra_gr_server.log 2>&1 &)"

- hosts: transmitters
  tasks:
    - name: Get source for GR-Hydra
      git:
        repo: "https://github.com/maiconkist/gr-hydra.git"
        dest: /home/ubuntu/gr-hydra
        version: bleeding
        update: true
        force: yes

    - name: "Create tap0 interface"
      shell: |
        ip tuntap add mode tap dev tap0
        ip addr add {{ tap0 }}/24 dev tap0
        ip link set dev tap0 up
      become: yes

    - name: "Create tap1 interface"
      shell: |
        ip tuntap add mode tap dev tap1
        ip addr add {{ tap1 }}/24 dev tap1
        ip link set dev tap1 up
      become: yes

    - name: chmod  /home/ubuntu/gr-hydra/grc_blocks/app/ansible_hydra_gr_client_2tx_2rx.py
      file:
        path: /home/ubuntu/gr-hydra/grc_blocks/app/ansible_hydra_gr_client_2tx_2rx.py
        state: file
        mode: a+x

    - name: Start ansible_hydra_gr_client_2tx_2rx.py script. Log to /tmp/
      shell: "(nohup python /home/ubuntu/gr-hydra/grc_blocks/app/ansible_hydra_gr_client_2tx_2rx.py --ansibleIP {{ hostvars[inventory_hostname]['ansible_ens4']['ipv4']['address'] }} </dev/null > /tmp/ansible_hydra_gr_client_2tx_2rx.log 2>&1 &)"


- hosts: rx1
  tasks:
    - name: Get source for GR-Hydra
      git:
        repo: "https://github.com/maiconkist/gr-hydra.git"
        dest: /home/ubuntu/gr-hydra
        version: bleeding
        update: true
        force: yes

    - name: "Create tap0 interface"
      shell: |
        ip tuntap add mode tap dev tap0
        ip addr add {{ tap0 }}/24 dev tap0
        ip link set dev tap0 up
      become: yes

    - name: chmod  /home/ubuntu/gr-hydra/grc_blocks/app/ansible_hydra_vr1_rx.py
      file:
        path: /home/ubuntu/gr-hydra/grc_blocks/app/ansible_hydra_vr1_rx.py
        state: file
        mode: a+x

    - name: Start ansible_vr1_rx.py script. Log to /tmp/
      shell: "(nohup python /home/ubuntu/gr-hydra/grc_blocks/app/ansible_hydra_vr1_rx.py </dev/null > /tmp/ansible_hydra_vr1_rx.log 2>&1 &)"

- hosts: rx2
  tasks:
    - name: Get source for GR-Hydra
      git:
        repo: "https://github.com/maiconkist/gr-hydra.git"
        dest: /home/ubuntu/gr-hydra
        version: bleeding
        update: true
        force: yes

    - name: "Create tap0 interface"
      shell: |
        ip tuntap add mode tap dev tap0
        ip addr add {{ tap0 }}/24 dev tap0
        ip link set dev tap0 up
      become: yes

    - name: chmod  /home/ubuntu/gr-hydra/grc_blocks/app/ansible_hydra_vr2_rx.py
      file:
        path: /home/ubuntu/gr-hydra/grc_blocks/app/ansible_hydra_vr2_rx.py
        state: file
        mode: a+x

    - name: Start ansible_vr2_rx.py script. Log to /tmp/
      shell: "(nohup python /home/ubuntu/gr-hydra/grc_blocks/app/ansible_hydra_vr2_rx.py </dev/null > /tmp/ansible_hydra_vr2_rx.log 2>&1 &)"
